# config.yaml

hyperparameters:
  lr_mu: 0.0005
  lr_q: 0.001
  gamma: 0.99
  batch_size: 32
  buffer_limit: 50000
  tau: 0.005

noise:
  theta: 0.1
  dt: 0.01
  sigma: 0.1

training:
  num_episodes: 1000
  print_interval: 20
  start_train_size: 200
  train_iterations: 10

environment:
  F_init : 140.0
  Ca_init : 2.2291
  Cb_init : 1.0417
  Ca_setpoint : 3.0
  sample_time : 0.5
  alpha : 1
  beta : 1
  delta : 0.1